### ISSUE TITLE
libSkinning.assign_weights_from_segments error

### ISSUE THREAD

**Issue by sbourgoing** [SqueezeStudioAnimation/omtk#1]
Got an issue at home when trying to build a dpSpine. The error is related to the OpenMaya MfnSkinCluster setWeight function which receive the wrong type of argument. I am currently not really setuped to debug this one right now and I also know that we never got this error back at Squeeze Studio.

It could be related to the OpenMaya version I have at home, but I don't have more information about this one. If I have some time in the next week, I will try to fix it on my side. For the moment, i will remove the call to this function and assign the ribbon skin manually

Here is the error logs:

```
# Traceback (most recent call last):
#   File "C:\Users\Sebastien\Documents\GitHub\omtk\scripts\omtk\uiLogic.py", line 524, in on_module_changed
#     module.build()
#   File "C:\Users\Sebastien\Documents\GitHub\omtk\scripts\omtk\core\classRig.py", line 335, in build
#     module.build(self, **kwargs)
#   File "C:\Users\Sebastien\Documents\GitHub\omtk\scripts\omtk\modules\rigDpSpine.py", line 145, in build
#     sys_ribbon.build(rig, create_ctrl=False, degree=3)
#   File "C:\Users\Sebastien\Documents\GitHub\omtk\scripts\omtk\modules\rigRibbon.py", line 78, in build
#     libSkinning.assign_weights_from_segments(self._ribbon_shape, self._ribbon_jnts, dropoff=1.0)
#   File "C:\Users\Sebastien\Documents\GitHub\omtk\scripts\omtk\libs\libSkinning.py", line 303, in assign_weights_from_segments
#     mfnSkinCluster.setWeights(geometryDagPath, component, mint_influences, new_weights, old_weights)
#   File "S:\Maya_2016_DI\build\Release\runTime\Python\Lib\site-packages\maya\OpenMayaAnim.py", line 1416, in setWeights
# NotImplementedError: # Wrong number or type of arguments for overloaded function 'MFnSkinCluster_setWeights'.
#   Possible C/C++ prototypes are:
#     setWeights(MFnSkinCluster *,MDagPath const &,MObject const &,unsigned int,double,bool,MDoubleArray *)
#     setWeights(MFnSkinCluster *,MDagPath const &,MObject const &,MIntArray &,MDoubleArray &,bool,MDoubleArray *)
#     setWeights(MFnSkinCluster *,MDagPath const &,MObject const &,unsigned int,float,bool,MFloatArray *)
    setWeights(MFnSkinCluster *,MDagPath const &,MObject const &,MIntArray &,MFloatArray &,bool,MFloatArray *)
# 

```

**Comment by sbourgoing** [comment]
Maybe it's related to my Maya version. I currently have not service pack installed. I will test that soon.

**Comment by sbourgoing** [comment]
I think it could be Windows related, because home the problem happen (Windows 10), but not at the job (CentOs 6.0). I would need to do more testing on windows station to see if this is really the problem.

**Comment by renaudll** [comment]
It seem that the reason of the crash is that the last argument of MFnSkinCluster.setWeights expect a pointer instead of a reference. I'm don't unserstand why it work in Linux but not on Windows. I'm not even sure that it is possible to pass a pointer using OpenMaya like we normally do for basic types with OpenMaya.MScriptUtils. Also MFnSkinCluster.setWeights don't register the undo correctly anyway, what a mess.

Since the 4th argument is optional, I've removed it and everything work fine now. If we absolutely want to register undo when transfering skin, we might want to move away from OpenMaya and using something else like cmds (slower) or the Maya API 2.0.
